### ISSUE TITLE
The database is automatically backed up every 3 minutes until the space is full

### ISSUE THREAD

**Issue by hermitguo** [Yenthe666/auto_backup#187]
environment：centos7X64 + docker19(odoo12 community/postgres10.0)，Setup: Backup once a day

In the beginning, the backup was normal. Then, for some reason, it often happened every 3 minutes. When **the hard disk space was full**, it would stop.

I uninstalled this module in the last two months, and the automatic backup will not happen every 3 minutes.

root@408722eca9fb:/mnt/backups# ls -lh
total 331G
-rw-r--r--. 1 odoo odoo  1.9G Jul  2 23:28 2020_07_02_15_25_06_odoo12.zip
-rw-r--r--. 1 odoo odoo     0 Jul  6 19:57 2020_07_06_11_57_49_odoo12.zip
-rw-r--r--. 1 odoo odoo  815M Jul  6 20:03 2020_07_06_12_01_50_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.4G Jul  6 20:06 2020_07_06_12_04_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:09 2020_07_06_12_07_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:12 2020_07_06_12_10_57_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 20:15 2020_07_06_12_13_59_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 20:19 2020_07_06_12_17_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:22 2020_07_06_12_20_03_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:25 2020_07_06_12_23_05_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:28 2020_07_06_12_26_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:31 2020_07_06_12_29_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:34 2020_07_06_12_32_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 20:37 2020_07_06_12_35_13_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:40 2020_07_06_12_38_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 20:43 2020_07_06_12_41_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:46 2020_07_06_12_44_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 20:49 2020_07_06_12_47_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  6 20:52 2020_07_06_12_50_22_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 20:55 2020_07_06_12_53_24_odoo12.zip
-rw-r--r--. 1 odoo odoo  981M Jul  6 20:58 2020_07_06_12_56_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  6 21:01 2020_07_06_12_59_29_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:04 2020_07_06_13_02_32_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 21:07 2020_07_06_13_05_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:10 2020_07_06_13_08_36_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:13 2020_07_06_13_11_39_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:16 2020_07_06_13_14_40_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:19 2020_07_06_13_17_42_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:22 2020_07_06_13_20_44_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:25 2020_07_06_13_23_46_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 21:28 2020_07_06_13_26_48_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:31 2020_07_06_13_29_50_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:34 2020_07_06_13_32_53_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  6 21:37 2020_07_06_13_35_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 21:40 2020_07_06_13_38_57_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:43 2020_07_06_13_41_59_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:47 2020_07_06_13_45_01_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 21:50 2020_07_06_13_48_03_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:53 2020_07_06_13_51_05_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 21:56 2020_07_06_13_54_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 21:59 2020_07_06_13_57_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:02 2020_07_06_14_00_13_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:05 2020_07_06_14_03_15_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:08 2020_07_06_14_06_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:11 2020_07_06_14_09_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:14 2020_07_06_14_12_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:17 2020_07_06_14_15_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:20 2020_07_06_14_18_25_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:23 2020_07_06_14_21_26_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:26 2020_07_06_14_24_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:29 2020_07_06_14_27_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:32 2020_07_06_14_30_33_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:35 2020_07_06_14_33_35_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:38 2020_07_06_14_36_37_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:41 2020_07_06_14_39_39_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:44 2020_07_06_14_42_41_odoo12.zip
-rw-r--r--. 1 odoo odoo  974M Jul  6 22:47 2020_07_06_14_45_43_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:50 2020_07_06_14_48_45_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:53 2020_07_06_14_51_47_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 22:56 2020_07_06_14_54_49_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 22:59 2020_07_06_14_57_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 23:02 2020_07_06_15_00_53_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 23:05 2020_07_06_15_03_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 23:08 2020_07_06_15_06_56_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 23:11 2020_07_06_15_09_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  6 23:15 2020_07_06_15_13_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 23:18 2020_07_06_15_16_02_odoo12.zip
-rw-r--r--. 1 odoo odoo  947M Jul  6 23:21 2020_07_06_15_19_05_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  6 23:24 2020_07_06_15_22_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  6 23:27 2020_07_06_15_25_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 00:21 2020_07_06_16_19_04_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.9G Jul  7 00:26 2020_07_06_16_23_15_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 00:29 2020_07_06_16_27_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.9G Jul  7 00:33 2020_07_06_16_30_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 00:36 2020_07_06_16_34_07_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 01:53 2020_07_06_17_51_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.7G Jul  7 01:56 2020_07_06_17_54_15_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:00 2020_07_06_17_58_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:03 2020_07_06_18_01_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:06 2020_07_06_18_04_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:09 2020_07_06_18_07_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.9G Jul  7 02:13 2020_07_06_18_10_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:16 2020_07_06_18_14_07_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:19 2020_07_06_18_17_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.5G Jul  7 02:22 2020_07_06_18_20_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.5G Jul  7 02:26 2020_07_06_18_23_52_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:29 2020_07_06_18_27_17_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:32 2020_07_06_18_30_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:35 2020_07_06_18_33_22_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:38 2020_07_06_18_36_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:41 2020_07_06_18_39_25_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:44 2020_07_06_18_42_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 02:47 2020_07_06_18_45_29_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.4G Jul  7 02:50 2020_07_06_18_48_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 02:53 2020_07_06_18_51_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:24 2020_07_07_00_22_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 08:27 2020_07_07_00_25_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 08:30 2020_07_07_00_28_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:33 2020_07_07_00_31_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 08:36 2020_07_07_00_34_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 08:39 2020_07_07_00_37_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:42 2020_07_07_00_40_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:45 2020_07_07_00_43_33_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:48 2020_07_07_00_46_35_odoo12.zip
-rw-r--r--. 1 odoo odoo  895M Jul  7 08:51 2020_07_07_00_49_37_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 08:54 2020_07_07_00_52_39_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 08:57 2020_07_07_00_55_41_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:00 2020_07_07_00_58_43_odoo12.zip
-rw-r--r--. 1 odoo odoo  948M Jul  7 09:03 2020_07_07_01_01_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:06 2020_07_07_01_04_54_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:09 2020_07_07_01_07_56_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:12 2020_07_07_01_10_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:16 2020_07_07_01_14_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:19 2020_07_07_01_17_03_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:22 2020_07_07_01_20_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:25 2020_07_07_01_23_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:28 2020_07_07_01_26_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:31 2020_07_07_01_29_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 09:34 2020_07_07_01_32_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:37 2020_07_07_01_35_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:40 2020_07_07_01_38_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 09:43 2020_07_07_01_41_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:46 2020_07_07_01_44_25_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 09:49 2020_07_07_01_47_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  912M Jul  7 09:52 2020_07_07_01_50_29_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:55 2020_07_07_01_53_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 09:58 2020_07_07_01_56_33_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:01 2020_07_07_01_59_35_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:04 2020_07_07_02_02_37_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:07 2020_07_07_02_05_39_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:10 2020_07_07_02_08_41_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:13 2020_07_07_02_11_43_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:16 2020_07_07_02_14_45_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:19 2020_07_07_02_17_47_odoo12.zip
-rw-r--r--. 1 odoo odoo  906M Jul  7 10:22 2020_07_07_02_20_48_odoo12.zip
-rw-r--r--. 1 odoo odoo  857M Jul  7 10:25 2020_07_07_02_23_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:28 2020_07_07_02_26_53_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:31 2020_07_07_02_29_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:34 2020_07_07_02_32_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:38 2020_07_07_02_36_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:41 2020_07_07_02_39_01_odoo12.zip
-rw-r--r--. 1 odoo odoo  980M Jul  7 10:44 2020_07_07_02_42_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:47 2020_07_07_02_45_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:50 2020_07_07_02_48_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 10:53 2020_07_07_02_51_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 10:56 2020_07_07_02_54_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 10:59 2020_07_07_02_57_22_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:02 2020_07_07_03_00_24_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:05 2020_07_07_03_03_26_odoo12.zip
-rw-r--r--. 1 odoo odoo 1012M Jul  7 11:08 2020_07_07_03_06_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  246M Jul  7 11:10 2020_07_07_03_09_30_odoo12.zip
-rw-r--r--. 1 odoo odoo  281M Jul  7 11:12 2020_07_07_03_11_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:15 2020_07_07_03_13_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:18 2020_07_07_03_16_57_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:22 2020_07_07_03_19_58_odoo12.zip
-rw-r--r--. 1 odoo odoo 1013M Jul  7 11:25 2020_07_07_03_23_01_odoo12.zip
-rw-r--r--. 1 odoo odoo  940M Jul  7 11:28 2020_07_07_03_26_03_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:31 2020_07_07_03_29_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:34 2020_07_07_03_32_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:37 2020_07_07_03_35_13_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:40 2020_07_07_03_38_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:43 2020_07_07_03_41_17_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:46 2020_07_07_03_44_19_odoo12.zip
-rw-r--r--. 1 odoo odoo  745M Jul  7 11:49 2020_07_07_03_47_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:52 2020_07_07_03_50_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 11:55 2020_07_07_03_53_26_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 11:58 2020_07_07_03_56_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 12:01 2020_07_07_03_59_30_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:04 2020_07_07_04_02_32_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 12:07 2020_07_07_04_05_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:10 2020_07_07_04_08_36_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:13 2020_07_07_04_11_40_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:16 2020_07_07_04_14_41_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 12:19 2020_07_07_04_17_43_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 12:22 2020_07_07_04_20_45_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 12:25 2020_07_07_04_23_49_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 12:28 2020_07_07_04_26_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 12:31 2020_07_07_04_29_54_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 12:34 2020_07_07_04_32_56_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 12:37 2020_07_07_04_35_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  387M Jul  7 12:40 2020_07_07_04_39_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:43 2020_07_07_04_41_04_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:46 2020_07_07_04_44_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:49 2020_07_07_04_47_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:52 2020_07_07_04_50_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:55 2020_07_07_04_53_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 12:58 2020_07_07_04_56_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 13:01 2020_07_07_04_59_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:04 2020_07_07_05_02_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 13:07 2020_07_07_05_05_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:10 2020_07_07_05_08_22_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:13 2020_07_07_05_11_24_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:16 2020_07_07_05_14_26_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:19 2020_07_07_05_17_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:22 2020_07_07_05_20_30_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:25 2020_07_07_05_23_32_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:28 2020_07_07_05_26_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:31 2020_07_07_05_29_36_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:34 2020_07_07_05_32_38_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:37 2020_07_07_05_35_40_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:40 2020_07_07_05_38_42_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:43 2020_07_07_05_41_44_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:46 2020_07_07_05_44_46_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:49 2020_07_07_05_47_48_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 13:52 2020_07_07_05_50_50_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 13:55 2020_07_07_05_53_52_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 13:58 2020_07_07_05_56_54_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:01 2020_07_07_05_59_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:05 2020_07_07_06_03_00_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 14:08 2020_07_07_06_06_02_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:11 2020_07_07_06_09_04_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:14 2020_07_07_06_12_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:17 2020_07_07_06_15_10_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:20 2020_07_07_06_18_12_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:23 2020_07_07_06_21_14_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:26 2020_07_07_06_24_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:29 2020_07_07_06_27_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 14:32 2020_07_07_06_30_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:35 2020_07_07_06_33_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:38 2020_07_07_06_36_25_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:41 2020_07_07_06_39_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:44 2020_07_07_06_42_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:47 2020_07_07_06_45_30_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 14:50 2020_07_07_06_48_32_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:53 2020_07_07_06_51_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 14:56 2020_07_07_06_54_36_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 14:59 2020_07_07_06_57_38_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:02 2020_07_07_07_00_40_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:05 2020_07_07_07_03_42_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 15:08 2020_07_07_07_06_44_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 15:11 2020_07_07_07_09_46_odoo12.zip
-rw-r--r--. 1 odoo odoo  961M Jul  7 15:14 2020_07_07_07_12_48_odoo12.zip
-rw-r--r--. 1 odoo odoo  996M Jul  7 15:17 2020_07_07_07_15_52_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 15:20 2020_07_07_07_18_54_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:23 2020_07_07_07_21_58_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 15:27 2020_07_07_07_25_01_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:30 2020_07_07_07_28_02_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 15:33 2020_07_07_07_31_05_odoo12.zip
-rw-r--r--. 1 odoo odoo 1019M Jul  7 15:36 2020_07_07_07_34_09_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 15:39 2020_07_07_07_37_11_odoo12.zip
-rw-r--r--. 1 odoo odoo  253M Jul  7 15:41 2020_07_07_07_40_13_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 15:45 2020_07_07_07_43_16_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:48 2020_07_07_07_46_18_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 15:51 2020_07_07_07_49_20_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:54 2020_07_07_07_52_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 15:57 2020_07_07_07_55_23_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:00 2020_07_07_07_58_26_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:03 2020_07_07_08_01_28_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 16:06 2020_07_07_08_04_30_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:09 2020_07_07_08_07_32_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:12 2020_07_07_08_10_34_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:15 2020_07_07_08_13_36_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:18 2020_07_07_08_16_38_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 16:21 2020_07_07_08_19_40_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:24 2020_07_07_08_22_45_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:27 2020_07_07_08_25_47_odoo12.zip
-rw-r--r--. 1 odoo odoo  251M Jul  7 16:29 2020_07_07_08_28_49_odoo12.zip
-rw-r--r--. 1 odoo odoo  959M Jul  7 16:32 2020_07_07_08_30_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:35 2020_07_07_08_33_53_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 16:38 2020_07_07_08_36_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 16:41 2020_07_07_08_39_57_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 16:45 2020_07_07_08_42_59_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 16:48 2020_07_07_08_46_02_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 16:51 2020_07_07_08_49_05_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 16:54 2020_07_07_08_52_06_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 16:57 2020_07_07_08_55_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:00 2020_07_07_08_58_11_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 17:03 2020_07_07_09_01_13_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:06 2020_07_07_09_04_19_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:09 2020_07_07_09_07_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.4G Jul  7 17:12 2020_07_07_09_10_22_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:15 2020_07_07_09_13_24_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 17:18 2020_07_07_09_16_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:21 2020_07_07_09_19_29_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:24 2020_07_07_09_22_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  962M Jul  7 17:27 2020_07_07_09_25_33_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 17:30 2020_07_07_09_28_35_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 17:33 2020_07_07_09_31_39_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:36 2020_07_07_09_34_41_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 17:39 2020_07_07_09_37_43_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 17:42 2020_07_07_09_40_45_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 17:45 2020_07_07_09_43_47_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 17:48 2020_07_07_09_46_49_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.4G Jul  7 17:51 2020_07_07_09_49_51_odoo12.zip
-rw-r--r--. 1 odoo odoo  295M Jul  7 17:53 2020_07_07_09_52_55_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 17:56 2020_07_07_09_54_56_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 18:00 2020_07_07_09_57_59_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 18:03 2020_07_07_10_01_03_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 18:06 2020_07_07_10_04_05_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 18:09 2020_07_07_10_07_07_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 18:12 2020_07_07_10_10_09_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 18:15 2020_07_07_10_13_11_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 20:08 2020_07_07_12_06_08_odoo12.zip
-rw-r--r--. 1 odoo odoo  2.1G Jul  7 20:12 2020_07_07_12_09_21_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 20:18 2020_07_07_12_16_24_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.3G Jul  7 20:32 2020_07_07_12_30_27_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.2G Jul  7 20:35 2020_07_07_12_33_31_odoo12.zip
-rw-r--r--. 1 odoo odoo  1.1G Jul  7 20:56 2020_07_07_12_54_34_odoo12.zip
-rw-r--r--. 1 odoo odoo     0 Jul  7 20:57 2020_07_07_12_57_36_odoo12.zip
-rw-r--r--. 1 odoo odoo     0 Jul  8 02:00 2020_07_07_18_00_07_odoo12.zip
root@408722eca9fb:/mnt/backups# rm -rf *.zip
root@408722eca9fb:/mnt/backups# 
root@408722eca9fb:/mnt/backups# 
root@408722eca9fb:/mnt/backups# df -lh
Filesystem               Size  Used Avail Use% Mounted on
overlay                  1.1T  743G  332G  70% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                    7.8G     0  7.8G   0% /sys/fs/cgroup
shm                       64M     0   64M   0% /dev/shm
/dev/mapper/centos-root  1.1T  743G  332G  70% /mnt/extra-addons
tmpfs                    7.8G     0  7.8G   0% /proc/asound
tmpfs                    7.8G     0  7.8G   0% /proc/acpi
tmpfs                    7.8G     0  7.8G   0% /proc/scsi
tmpfs                    7.8G     0  7.8G   0% /sys/firmware
root@408722eca9fb:/mnt/backups# cd /tmp
root@408722eca9fb:/tmp# dir
sale_export.xlsx  tmp1brtxfhn  tmp2tudvgh7  tmp3utls6eu  tmp53vv0z2s  tmp66tlgmef  tmp7sc6squv	tmp8xies2li  tmp_02xy5id  tmpaepua909  tmpb53v
tmp0ass51x3	  tmp1i8i_yt0  tmp30zreck5  tmp490bpcfn  tmp54uqmwvx  tmp6a8l24mp  tmp816vmi6w	tmp8yg5ho0r  tmp_3ynt008  tmpahenqide  tmpb5q7
tmp0dkm63_p	  tmp1je5b0dy  tmp37fhnw10  tmp49hq7wbw  tmp5attt9gu  tmp6c60_uq1  tmp81ppgo6x	tmp996_h0we  tmp__bdievz  tmpaj0lh522  tmpb7fe
tmp0e4x5nc_	  tmp1lwd5kl0  tmp3bgkmkh4  tmp4olqcvrx  tmp5et0dq_n  tmp6g5sd0bh  tmp8au9jgdp	tmp9a4k4ipx  tmp_daaf5ng  tmpajb1mkyr  tmpbehx
tmp0h8bsjr4	  tmp1pepuktq  tmp3fm8dj0h  tmp4r1amjtg  tmp5i_gvsqf  tmp6p_xvnsn  tmp8ch0kdt8	tmp9anbgnu9  tmp_r0nx_nh  tmpakxbecdq  tmpbvh3
tmp0uysvg1p	  tmp1vwtgpty  tmp3pg4n4bi  tmp4td2l1k3  tmp5irpbrop  tmp71okapd7  tmp8km5txur	tmp9nohlubv  tmp_y3x8dwf  tmpan2e9_ng  tmpbwbn
tmp0v1bteos	  tmp26dle0e4  tmp3qv0n8ad  tmp4tm6gkge  tmp5k9licx6  tmp7arb0su8  tmp8sl460jw	tmp9ptir8ah  tmpa071im9s  tmpaq7lxt_w  tmpbyv0
tmp179fx24_	  tmp2dpj5uin  tmp3t5vp_2x  tmp4zaaxx2k  tmp5rqf_6gg  tmp7p5klhnx  tmp8sntlgay	tmp9sargi50  tmpa0w06vlg  tmparb19_g9  tmpc73h
tmp194j6am0	  tmp2gkyfa4n  tmp3taas4n6  tmp51zd1ayk  tmp5zs2jega  tmp7qggqv0n  tmp8tzpppls	tmp9upp34c6  tmpady9zslj  tmpavdtf40l  tmpc_39
root@408722eca9fb:/tmp# 
root@408722eca9fb:/tmp# du -sh /tmp
727G	/tmp

**Comment by NCS-75** [comment]
Hi
Same thing here..

Environment：Frontend-Backend =All local, no sftp
ubuntu 18.04 (odoo13 community/postgres10.0)，Setup: Backup once a day.
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 4800
max_cron_threads = 2

Contexte :
This happends from the time,  once the server has ran out of space , and fails down, due to dayly multi backup action running.
Then, to retreive space, i have deleted some unwanted zip backup files , in a directory, and  could  imagine that may resolve the situation. Nop, backup action still run infinitly !

Consideration :
The backup  cron is always runing, then, impossible to stop it, from odoo !
I will try to modify a field into the database table "ir.cron ?" (cron not active) to resolve.
Otherwise, i will try to force uninstall the backup module.

Disk space issue situation, happends sometime  (eg: logs gowing, ans so on..)
So, i guess i need to go to the code to avoid facing again this referenced issue 

@Yenthe666 Any idea ? 
---------------------------------------------------------------------------------------------------------
Below, one of my multiples backup directories ; it's same situation for others...

root@odoo-13:/opt/odoo_backups/db_backups/backup_template-db# ls -lh
total 205M
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 16:56 2020_09_04_14_56_22_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 17:53 2020_09_04_15_53_05_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 18:00 2020_09_04_16_00_40_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 18:33 2020_09_04_16_33_01_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 19:05 2020_09_04_17_04_56_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 21:28 2020_09_04_19_27_54_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 21:36 2020_09_04_19_36_03_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 21:49 2020_09_04_19_49_05_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 22:00 2020_09_04_20_00_07_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 22:05 2020_09_04_20_05_02_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 22:14 2020_09_04_20_14_33_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  4 22:34 2020_09_04_20_34_41_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:41 2020_09_05_09_41_35_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:43 2020_09_05_09_43_35_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:45 2020_09_05_09_45_27_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:46 2020_09_05_09_46_54_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:47 2020_09_05_09_47_49_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:48 2020_09_05_09_48_52_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:51 2020_09_05_09_51_21_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:52 2020_09_05_09_52_13_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:53 2020_09_05_09_53_02_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:53 2020_09_05_09_53_46_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:54 2020_09_05_09_54_30_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:55 2020_09_05_09_55_06_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:55 2020_09_05_09_55_48_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:56 2020_09_05_09_56_33_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:57 2020_09_05_09_57_13_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:57 2020_09_05_09_57_53_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:58 2020_09_05_09_58_28_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:58 2020_09_05_09_58_50_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:59 2020_09_05_09_59_12_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:59 2020_09_05_09_59_33_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 11:59 2020_09_05_09_59_53_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:00 2020_09_05_10_00_12_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:00 2020_09_05_10_00_32_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:00 2020_09_05_10_00_51_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:01 2020_09_05_10_01_12_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:01 2020_09_05_10_01_29_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:01 2020_09_05_10_01_46_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:02 2020_09_05_10_02_01_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:02 2020_09_05_10_02_16_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:02 2020_09_05_10_02_32_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:02 2020_09_05_10_02_47_Template.zip
-rw-r--r-- 1 odoo odoo 4.7M Sep  5 12:03 2020_09_05_10_03_04_Template.zip
-rw-r--r-- 1 odoo odoo 1.1M Sep  5 12:03 2020_09_05_10_03_17_Template.zip
-rw-r--r-- 1 odoo odoo 4.6K Sep  5 12:03 2020_09_05_10_03_32_Template.zip

**Comment by Yenthe666** [comment]
This _can_ happen if you have a big database and your cron times out before it finishes. In this case it will re-try again and the same loop seems to go off again. I haven't found a reproducable step/fix yet though

**Comment by chalsbcn** [comment]
Hi, I found this yesterday, https://www.moldeointeractive.com.ar/blog/moldeo-interactive-1/post/problemas-de-performance-ocasionados-por-el-ir-cron-de-odoo-749
tried it, and my performance issues have been fixed. @Yenthe666 what do you think?

**Comment by Yenthe666** [comment]
Well, that is kinda a way around it. Sure, it deactivates it & stops the loop but it doesn't really fix the underlying issue so at some point it comes back up 🤔

**Comment by hermitguo** [comment]
Hello Sir,

Thank you very munch!

Best regards,
 
From: chalsbcn
Date: 2021-05-19 17:15
To: Yenthe666/auto_backup
CC: eremiter; Author
Subject: Re: [Yenthe666/auto_backup] The database is automatically backed up every 3 minutes until the space is full (#187)
Hi, I found this yesterday, https://www.moldeointeractive.com.ar/blog/moldeo-interactive-1/post/problemas-de-performance-ocasionados-por-el-ir-cron-de-odoo-749
tried it, and my performance issues have been fixed. @Yenthe666 what do you think?

**Comment by samahkandil** [comment]
Hi @Yenthe666 i has a problem in back it takes many backup for same day , around 50 times , if you has a solution for this problem or stop back and delete it if it failure ?

**Comment by Yenthe666** [comment]
Probably delete the backups on both the local & remote disk and then plan the scheduler in the future again. If you have a really big database it'll blow up again most likely though.
Usually this happens when the timeouts from your Odoo config file are shorter than the time it takes to create it is longer & it keeps trying

**Comment by unjoss** [comment]
I have similar issue, version 13 CE and ubuntu 18. backup to local folder and is set to execute once a day in the morning but it creates a lot of backups files and it fills the backup dir and also seems to fill up the /tmp directory.  I executed the job from the odoo menu and it seems to work fine it generates a single backup .zip files and its size is about 1GigaByte.  backup folder has 100GB of storage and /tmp has about 60Gb storage.

Also I notice that the generated file name does not have the same date as server does.

Server date:
https://imguploader.net/images/WOcl5tJEinNJ

Files generated
https://imguploader.net/images/Nbrgre8NBsnp

Schedule
https://imguploader.net/images/zx5hIYQpDkTe

Backup setting
https://imguploader.net/images/QEoqwARqKOdZ

**Comment by unjoss** [comment]
in my case it seems setting max_cron_threads = 1  solved the issue,  5 days in a row and no duplicates backup files.

**Comment by Yenthe666** [comment]
o_O Do you see timeouts in the logs which rejumped this cron?

**Comment by unjoss** [comment]
> o_O Do you see timeouts in the logs which rejumped this cron?

I don't know how to search for that. If you point me how I'll check it

**Comment by Yenthe666** [comment]
Check your logs to see if you see any crons crashing (usually under /var/log/odoo).
You can do a grep on "ERROR" and then usually they come up. E.g:
`sudo grep -Rn "ERROR" /var/log/odoo/name_of_your_log.log`

**Comment by unjoss** [comment]
here is the output, it seems not recent errors

xdev@oserver:~$ sudo grep -Rn "ERROR" /var/log/odoo13c/odoo13c-server.log
365:2020-12-18 16:23:28,148 7901 ERROR dev_base_modules2 odoo.modules.loading: Some modules are not loaded, some dependencies or manifest may be missing: ['base_partner_sequence', 'base_search_custom_field_filter', 'partner_credit_limit', 'partner_ref_unique', 'partner_statement', 'product_code_unique', 'product_manufacturer', 'product_sequence', 'sale_quotation_number']
392:2020-12-18 16:23:41,394 7901 ERROR dev_base_modules2 odoo.addons.base.models.ir_model: Missing model ir.ui.custom.field.filter
415:2020-12-18 16:23:47,099 7901 ERROR dev_base_modules2 odoo.addons.base.models.ir_model: Missing model ir.ui.custom.field.filter
436:2020-12-18 16:23:53,953 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
495:2020-12-18 16:24:22,889 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
553:2020-12-18 16:24:35,355 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
607:2020-12-18 16:24:41,484 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
665:2020-12-18 16:33:53,535 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
729:2020-12-18 16:34:09,759 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
1796:2020-12-19 17:20:33,532 7901 ERROR dev_base_modules2 odoo.addons.base.models.ir_model: Missing model ir.ui.custom.field.filter
1822:2020-12-19 17:21:19,496 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
1870:2020-12-19 17:21:28,927 7901 ERROR dev_base_modules2 odoo.addons.base.models.ir_model: Missing model ir.ui.custom.field.filter
1882:2020-12-19 17:21:31,584 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
1950:2020-12-19 17:22:01,155 7901 ERROR dev_base_modules2 odoo.http: Exception during JSON request handling.
2011:2020-12-19 17:23:55,364 7901 ERROR dev_base_modules2 werkzeug: Error on request:
12872:2020-12-21 18:36:44,319 7901 ERROR dev_conf03_th odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "name") VALUES (nextval('res_country_state_id_seq'), 6, (now() at time zone 'UTC'), 6, (now() at time zone 'UTC'), 'Cortes') RETURNING id
12873:ERROR: null value in column "country_id" violates not-null constraint
13182:2020-12-21 19:29:52,466 7901 ERROR dev_conf03_th odoo.addons.mail.models.mail_mail: failed sending mail (id: 12) due to Fallo de entrega de correo
Binary file /var/log/odoo13c/odoo13c-server.log matches
xdev@oserver:~$

**Comment by Yenthe666** [comment]
How can the things in your log be from 2020-12-12? Are you sure you went all the way down and had the current logfile open?

**Comment by unjoss** [comment]
2021 ?   not sure why the paste did not show properly,  I see only dates from 2020

https://pastebin.com/D3gF2rnU

**Comment by Yenthe666** [comment]
Typo :) I mean I don't get why there is nothing in there for 2021.. It's been 7+ months :)

**Comment by unjoss** [comment]
hahaha I also noticed that and is kinda weird, but I cheked and the log file it seems to be working ok it has plenty of messages everyday including today, but rows with the string "ERROR" none in this year.

**Comment by Yenthe666** [comment]
Hmm do you find something in the log about "killed"?

**Comment by unjoss** [comment]
no rows found with "killed" or "KILLED",   also tried with "kill" but only shows 2 rows from 2020.

**Comment by naysonrussier** [comment]
limit_time_real_cron solved the issue for me
