### ISSUE TITLE
I installed module on odoo.sh but created backup file with 0 size.

### ISSUE THREAD

**Issue by sagars-emipro** [Yenthe666/auto_backup#271]
Hello, 
I configured module on odoo.sh and try to backup. 
So, created backup file and transfer to another server but, backup file size is 0.
Can you please provide solution?

**Comment by randall-vx** [comment]
Solved in #272 

cc: @Yenthe666

**Comment by sagars-emipro** [comment]
I have applied changes. but still getting same issue.
![image](https://github.com/Yenthe666/auto_backup/assets/87762796/17b3f831-bc6e-4d85-8775-b0b6d7bef65c)

cc: @Yenthe666

**Comment by yangyongyy55** [comment]
If Odoo and PostgreSQL are not on the same server, for example, when using Docker installation, you may encounter the issue where the backup size is 0KB. You can try mounting the same directory to /var/run/postgresql on both the Odoo and PostgreSQL containers, for example: /yourpath:/var/run/postgresql
Or change the database connection from a socket to a TCP connection.
